name: Publish Contentful
on:
  repository_dispatch:
    types: [contentful-publish]
jobs:
  rebuild:
    runs-on: self-hosted
    steps:
      - name: Rebuild image
        run: |
          $HOME/${{ secrets.CONTENTFUL_REBUILD_SCRIPT_PATH }}
      - name: Run deploy script
        run: |
          $HOME/${{ secrets.DEPLOY_SCRIPT_PATH }}
